Update demo.py
Fixed this error:
```
Pipeline started
Traceback (most recent call last):
  File "demo.py", line 208, in <module>
    cv2.rectangle(frame, zone[:2], zone[2:], color, 3)
TypeError: an integer is required (got type tuple)
```